(() => {
'use strict';
const SUPABASE_URL='https://keucuxicejohafnokfkz.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_kytuO_i7LSXusij9nc0B3g_ZvOpcIrZ';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const state={user:null,profile:null,organizations:[],conversations:[],leads:[],assistants:[],knowledge:[],selectedConversationId:null,channels:[]};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=v=>v?new Date(v).toLocaleString([],{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—';
const initials=n=>(n||'SL').split(/\s+/).filter(Boolean).map(x=>x[0]).join('').slice(0,2).toUpperCase();
const slugify=s=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,42);
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)};
const fail=(m,e)=>{console.error(m,e);toast(e?.message||m)};
const orgName=id=>state.organizations.find(o=>o.id===id)?.name||'Unknown client';
function showLogin(message=''){ $('#appShell').classList.add('hidden');$('#authGate').style.display='grid';$('#authError').textContent=message; }
async function requireAdmin(){const {data:{user},error:userError}=await db.auth.getUser();if(userError||!user)return showLogin();const {data:profile,error}=await db.from('profiles').select('id,full_name,role,avatar_url').eq('id',user.id).single();if(error||!profile||profile.role!=='admin'){await db.auth.signOut();return showLogin('This account does not have platform administrator access.')}state.user=user;state.profile=profile;$('#authGate').style.display='none';$('#appShell').classList.remove('hidden');const name=profile.full_name||user.email||'Administrator';$('#profileName').textContent=name;$('#profileInitials').textContent=initials(name);$('#welcomeTitle').textContent=`Welcome, ${name}.`;$('#settingsName').value=profile.full_name||'';$('#settingsEmail').value=user.email||'';$('#settingsUserId').value=user.id;await loadAll();subscribeRealtime();}
async function loadAll(){document.body.classList.add('loading');try{const [orgs,convs,leads,assistants,knowledge]=await Promise.all([db.from('organizations').select('id,name,slug,plan,subscription_status,onboarding_completed,notification_email,created_at,updated_at').order('created_at',{ascending:false}),db.from('conversations').select('id,organization_id,assistant_id,visitor_name,visitor_email,status,started_at,updated_at,ai_enabled,last_message_at').order('last_message_at',{ascending:false}).limit(250),db.from('leads').select('id,organization_id,conversation_id,name,email,phone,notes,status,created_at,updated_at').order('created_at',{ascending:false}).limit(500),db.from('assistants').select('id,organization_id,name,description,status,greeting,primary_color,created_at,updated_at').order('created_at',{ascending:false}),db.from('knowledge_sources').select('id,organization_id,assistant_id,name,source_type,source_url,status,created_at,updated_at').order('created_at',{ascending:false})]);for(const r of [orgs,convs,leads,assistants,knowledge])if(r.error)throw r.error;state.organizations=orgs.data||[];state.conversations=convs.data||[];state.leads=leads.data||[];state.assistants=assistants.data||[];state.knowledge=knowledge.data||[];renderAll()}catch(e){fail('Could not load dashboard data',e)}finally{document.body.classList.remove('loading')}}
function renderAll(){$('#clientNavCount').textContent=state.organizations.length;$('#conversationNavCount').textContent=state.conversations.length;$('#leadNavCount').textContent=state.leads.length;$('#statClients').textContent=state.organizations.length;$('#statConversations').textContent=state.conversations.length;$('#statLeads').textContent=state.leads.length;$('#statAssistants').textContent=state.assistants.length;renderOverview();renderClients();renderThreads();renderLeads();renderAssistants();renderKnowledge();renderAnalytics();populateOrgSelects()}
function renderOverview(){$('#clientList').innerHTML=state.organizations.slice(0,5).map(o=>`<div class="clientRow"><span class="clientLogo">${esc(initials(o.name))}</span><div class="clientInfo"><b>${esc(o.name)}</b><span>${esc(o.plan)} · ${esc(o.subscription_status)}</span></div><small class="usageText">${fmt(o.created_at)}</small></div>`).join('')||'<div class="empty">No clients yet.</div>';$('#leadList').innerHTML=state.leads.slice(0,5).map(l=>`<div class="leadRow"><span class="leadAvatar">${esc(initials(l.name||l.email))}</span><div class="leadInfo"><b>${esc(l.name||l.email||'Unnamed lead')}</b><span>${esc(orgName(l.organization_id))} · ${esc(l.status)}</span></div><small class="usageText">${fmt(l.created_at)}</small></div>`).join('')||'<div class="empty">No leads yet.</div>'}
function renderClients(){const rows=state.organizations;$('#clientsTable').innerHTML=`<table class="table"><thead><tr><th>Client</th><th>Plan</th><th>Subscription</th><th>Onboarding</th><th>Email</th><th>Created</th></tr></thead><tbody>${rows.map(o=>`<tr><td><b>${esc(o.name)}</b><br><small>${esc(o.slug)}</small></td><td>${esc(o.plan)}</td><td><span class="pill">${esc(o.subscription_status)}</span></td><td>${o.onboarding_completed?'Complete':'Pending'}</td><td>${esc(o.notification_email||'—')}</td><td>${fmt(o.created_at)}</td></tr>`).join('')}</tbody></table>`}
function renderThreads(){$('#threadList').innerHTML=state.conversations.map(c=>`<div class="thread ${state.selectedConversationId===c.id?'active':''}" data-conversation="${c.id}"><div class="threadTop"><b>${esc(c.visitor_name||c.visitor_email||'Visitor')}</b><small>${fmt(c.last_message_at)}</small></div><small>${esc(orgName(c.organization_id))} · ${esc(c.status)}</small><p>${c.ai_enabled?'AI enabled':'Human handling'}</p></div>`).join('')||'<div class="empty">No conversations yet.</div>';$$('[data-conversation]').forEach(el=>el.onclick=()=>openConversation(el.dataset.conversation))}
async function openConversation(id){state.selectedConversationId=id;renderThreads();const c=state.conversations.find(x=>x.id===id);if(!c)return;const pane=$('#conversation');pane.innerHTML='<div class="empty conversationEmpty">Loading messages…</div>';const {data,error}=await db.from('messages').select('id,sender_type,content,created_at').eq('conversation_id',id).order('created_at');if(error)return fail('Could not load messages',error);pane.innerHTML=`<div class="conversationHead"><b>${esc(c.visitor_name||c.visitor_email||'Visitor')}</b><div>${esc(orgName(c.organization_id))} · ${esc(c.status)}</div></div><div class="messages">${(data||[]).map(m=>`<div class="message ${['agent','ai','assistant'].includes(m.sender_type)?'agent':''}">${esc(m.content)}<small>${esc(m.sender_type)} · ${fmt(m.created_at)}</small></div>`).join('')||'<div class="empty">No messages.</div>'}</div><form class="replyBox" id="replyForm"><input name="message" autocomplete="off" placeholder="Type a human reply…" required><button class="primaryBtn" type="submit">Send</button></form>`;$('#replyForm').onsubmit=async e=>{e.preventDefault();const content=new FormData(e.currentTarget).get('message').trim();if(!content)return;const {error:sendError}=await db.from('messages').insert({organization_id:c.organization_id,conversation_id:c.id,sender_type:'agent',content});if(sendError)return fail('Reply failed',sendError);await db.from('conversations').update({ai_enabled:false,updated_at:new Date().toISOString(),last_message_at:new Date().toISOString()}).eq('id',c.id);toast('Reply sent');await openConversation(c.id);await loadAll()}}
function renderLeads(){$('#leadsTable').innerHTML=`<table class="table"><thead><tr><th>Lead</th><th>Client</th><th>Contact</th><th>Status</th><th>Notes</th><th>Created</th></tr></thead><tbody>${state.leads.map(l=>`<tr><td><b>${esc(l.name||'Unnamed')}</b></td><td>${esc(orgName(l.organization_id))}</td><td>${esc(l.email||l.phone||'—')}</td><td><select data-lead-status="${l.id}">${['new','contacted','qualified','won','lost'].map(s=>`<option value="${s}" ${l.status===s?'selected':''}>${s[0].toUpperCase()+s.slice(1)}</option>`).join('')}</select></td><td>${esc(l.notes||'—')}</td><td>${fmt(l.created_at)}</td></tr>`).join('')}</tbody></table>`;$$('[data-lead-status]').forEach(sel=>sel.onchange=async()=>{const {error}=await db.from('leads').update({status:sel.value,updated_at:new Date().toISOString()}).eq('id',sel.dataset.leadStatus);if(error)return fail('Could not update lead',error);toast('Lead status updated');await loadAll()})}
function renderAssistants(){$('#assistantGrid').innerHTML=state.assistants.map(a=>`<article class="assistantCard"><div class="assistantCardTop"><span class="assistantIcon">◆</span><span class="pill">${esc(a.status)}</span></div><h3>${esc(a.name)}</h3><p>${esc(a.description||a.greeting||'ServeLink AI assistant')}</p><div class="assistantMetrics"><div><b>${esc(orgName(a.organization_id))}</b><span>Organization</span></div><div><b>${fmt(a.updated_at)}</b><span>Updated</span></div></div><button class="secondaryBtn" data-toggle-assistant="${a.id}" data-status="${esc(a.status)}">${a.status==='active'?'Pause':'Activate'}</button></article>`).join('')||'<div class="empty">No assistants yet.</div>';$$('[data-toggle-assistant]').forEach(btn=>btn.onclick=async()=>{const next=btn.dataset.status==='active'?'paused':'active';const {error}=await db.from('assistants').update({status:next,updated_at:new Date().toISOString()}).eq('id',btn.dataset.toggleAssistant);if(error)return fail('Could not update assistant',error);toast(`Assistant ${next}`);await loadAll()})}
function renderKnowledge(){$('#docList').innerHTML=state.knowledge.map(k=>`<div class="docRow"><span class="docIcon">▤</span><div><b>${esc(k.name)}</b><small>${esc(orgName(k.organization_id))} · ${esc(k.source_type)} · ${esc(k.status)}</small></div><small class="usageText">${fmt(k.updated_at)}</small></div>`).join('')||'<div class="empty">No knowledge sources yet.</div>'}
function renderAnalytics(){const open=state.conversations.filter(c=>!['closed','resolved'].includes(String(c.status).toLowerCase())).length,qualified=state.leads.filter(l=>['qualified','won'].includes(String(l.status).toLowerCase())).length,active=state.assistants.filter(a=>String(a.status).toLowerCase()==='active').length;$('#analyticsOpen').textContent=open;$('#analyticsQualified').textContent=qualified;$('#analyticsActiveAI').textContent=active;$('#analyticsKnowledge').textContent=state.knowledge.length;const groups={};state.leads.forEach(l=>groups[l.status||'unknown']=(groups[l.status||'unknown']||0)+1);const vals=Object.entries(groups),max=Math.max(1,...vals.map(v=>v[1]));$('#topicBars').innerHTML=vals.map(([label,val])=>`<div class="topicRow"><b>${esc(label)}</b><div class="topicBar"><i style="width:${Math.round(val/max*100)}%"></i></div><span>${val}</span></div>`).join('')||'<div class="empty">No lead data yet.</div>'}
function populateOrgSelects(){const options=state.organizations.map(o=>`<option value="${o.id}">${esc(o.name)}</option>`).join('');$('#assistantOrg').innerHTML=options;$('#knowledgeOrg').innerHTML=options}
function subscribeRealtime(){state.channels.forEach(ch=>db.removeChannel(ch));state.channels=[];['organizations','conversations','messages','leads','assistants','knowledge_sources'].forEach(table=>{const ch=db.channel(`admin-${table}`).on('postgres_changes',{event:'*',schema:'public',table},async payload=>{if(table==='messages'&&state.selectedConversationId&&(payload.new?.conversation_id===state.selectedConversationId||payload.old?.conversation_id===state.selectedConversationId))await openConversation(state.selectedConversationId);await loadAll()}).subscribe();state.channels.push(ch)})}
function switchView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.navItem').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('#sidebar').classList.remove('open');$('#mobileShade').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
function openModal(id){$('#'+id).classList.add('open')}function closeModal(id){$('#'+id).classList.remove('open')}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#authError').textContent='';const {error}=await db.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});if(error)return showLogin(error.message);await requireAdmin()};
$('#signOutBtn').onclick=async()=>{await db.auth.signOut();location.reload()};$('#refreshBtn').onclick=loadAll;$('#menuBtn').onclick=()=>{$('#sidebar').classList.add('open');$('#mobileShade').classList.add('open')};$('#mobileShade').onclick=()=>{$('#sidebar').classList.remove('open');$('#mobileShade').classList.remove('open')};$$('.navItem').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>switchView(b.dataset.jump));$$('[data-modal]').forEach(b=>b.onclick=()=>openModal(b.dataset.modal));$$('.closeModal').forEach(b=>b.onclick=()=>closeModal(b.closest('.modal').id));$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)closeModal(m.id)});
$('#clientForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),name=f.get('name').trim(),row={name,slug:`${slugify(name)}-${Date.now().toString().slice(-6)}`,created_by:state.user.id,plan:f.get('plan'),subscription_status:'active',notification_email:f.get('email')||null};const {error}=await db.from('organizations').insert(row);if(error)return fail('Could not create client',error);e.currentTarget.reset();closeModal('clientModal');toast('Client created');await loadAll()};
$('#assistantForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),row={organization_id:f.get('organization_id'),name:f.get('name').trim(),greeting:f.get('greeting').trim()||'Hi! How can I help today?',system_prompt:f.get('system_prompt').trim()||null,status:'draft',created_by:state.user.id};const {error}=await db.from('assistants').insert(row);if(error)return fail('Could not create assistant',error);e.currentTarget.reset();closeModal('assistantModal');toast('Assistant created');await loadAll()};
$('#knowledgeForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),row={organization_id:f.get('organization_id'),name:f.get('name').trim(),source_type:f.get('source_type'),source_url:f.get('source_url')||null,raw_text:f.get('raw_text').trim(),status:'ready'};const {error}=await db.from('knowledge_sources').insert(row);if(error)return fail('Could not add knowledge source',error);e.currentTarget.reset();closeModal('knowledgeModal');toast('Knowledge source added');await loadAll()};
$('#settingsForm').onsubmit=async e=>{e.preventDefault();const full_name=$('#settingsName').value.trim(),{error}=await db.from('profiles').update({full_name,updated_at:new Date().toISOString()}).eq('id',state.user.id);if(error)return fail('Could not save profile',error);state.profile.full_name=full_name;$('#profileName').textContent=full_name;$('#profileInitials').textContent=initials(full_name);$('#welcomeTitle').textContent=`Welcome, ${full_name||'Administrator'}.`;toast('Profile saved')};
$('#downloadLeads').onclick=()=>{const rows=[['Name','Email','Phone','Client','Status','Created'],...state.leads.map(l=>[l.name||'',l.email||'',l.phone||'',orgName(l.organization_id),l.status||'',l.created_at||''])],csv=rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='servelink-leads.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('Lead export downloaded')};
$('#globalSearch').oninput=e=>{const q=e.target.value.trim().toLowerCase();if(q.length<2)return;const hit=state.organizations.find(o=>o.name.toLowerCase().includes(q))||state.leads.find(l=>`${l.name||''} ${l.email||''}`.toLowerCase().includes(q))||state.conversations.find(c=>`${c.visitor_name||''} ${c.visitor_email||''}`.toLowerCase().includes(q));if(hit)toast(`Found: ${hit.name||hit.visitor_name||hit.email||hit.visitor_email||'record'}`)};
db.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT')showLogin()});requireAdmin();
})();
