const clients=[{name:'Summit HVAC',industry:'Home Services',plan:'Growth',status:'Active',usage:'684 / 1,000',initials:'SH'},{name:'BrightSmile Dental',industry:'Healthcare',plan:'Growth',status:'Active',usage:'492 / 1,000',initials:'BD'},{name:'Harrison Legal Group',industry:'Legal',plan:'Launch',status:'Active',usage:'318 / 500',initials:'HL'},{name:'Metro Auto Care',industry:'Automotive',plan:'Launch',status:'Setup',usage:'348 / 500',initials:'MA'}];
const leads=[{name:'Marcus Reed',company:'Summit HVAC',need:'Emergency AC repair',value:'$850',time:'8 min ago'},{name:'Taylor Brooks',company:'BrightSmile Dental',need:'New patient exam',value:'$320',time:'24 min ago'},{name:'Dana Lewis',company:'Harrison Legal Group',need:'Business consultation',value:'$1,500',time:'1 hr ago'},{name:'Alex Morgan',company:'Metro Auto Care',need:'Brake inspection',value:'$420',time:'2 hrs ago'}];
const threads=[{name:'Marcus Reed',company:'Summit HVAC',preview:'My AC stopped cooling this afternoon...',time:'8m',messages:[['customer','My AC stopped cooling this afternoon. Can someone come tomorrow?'],['ai','I can help with that. Is the system running but blowing warm air, or is it completely off?'],['customer','It is running but blowing warm air.'],['ai','Thanks. I have captured an urgent cooling repair request for tomorrow. May I have your ZIP code and phone number?']]},{name:'Taylor Brooks',company:'BrightSmile Dental',preview:'Do you accept new patients?',time:'24m',messages:[['customer','Do you accept new patients?'],['ai','Yes, BrightSmile Dental is accepting new patients. Would you like to see available appointment times?']]},{name:'Dana Lewis',company:'Harrison Legal Group',preview:'I need help with a business contract...',time:'1h',messages:[['customer','I need help reviewing a business contract.'],['ai','I can collect a few details and request a consultation. What type of contract is involved?']]}];
const documents=[['Service Catalog.pdf','Summit HVAC','Updated today'],['Frequently Asked Questions.docx','BrightSmile Dental','Updated yesterday'],['Consultation Policies.txt','Harrison Legal Group','Updated 3 days ago'],['https://metroautocare.com/services','Metro Auto Care','Synced 1 hour ago']];
const assistants=[['Summit Service Assistant','Summit HVAC','Live','684','89%'],['BrightSmile Concierge','BrightSmile Dental','Live','492','91%'],['Harrison Intake Assistant','Harrison Legal Group','Live','318','83%'],['Metro Auto Helper','Metro Auto Care','Setup','348','78%']];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function switchView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.navItem').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('#sidebar').classList.remove('open');$('#mobileShade').classList.remove('open');window.scrollTo(0,0)}
$$('.navItem').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>switchView(b.dataset.jump));
$('#menuBtn').onclick=()=>{$('#sidebar').classList.add('open');$('#mobileShade').classList.add('open')};$('#mobileShade').onclick=()=>{$('#sidebar').classList.remove('open');$('#mobileShade').classList.remove('open')};
function renderOverview(){const cl=$('#clientList');cl.innerHTML=clients.map(c=>`<div class="clientRow"><span class="clientLogo">${c.initials}</span><div class="clientInfo"><b>${c.name}</b><span>${c.industry} · ${c.plan}</span></div><span class="pill">${c.status}</span><span class="usageText">${c.usage}<br>conversations</span></div>`).join('');$('#leadList').innerHTML=leads.slice(0,4).map(l=>`<div class="leadRow"><span class="leadAvatar">${l.name.split(' ').map(x=>x[0]).join('')}</span><div class="leadInfo"><b>${l.name}</b><span>${l.company} · ${l.need}</span></div><div class="usageText"><b>${l.value}</b><br>${l.time}</div></div>`).join('')}
function renderClients(){let h='<table class="table"><thead><tr><th>Client</th><th>Industry</th><th>Plan</th><th>Status</th><th>Usage</th><th></th></tr></thead><tbody>';h+=clients.map(c=>`<tr><td><b>${c.name}</b></td><td>${c.industry}</td><td>${c.plan}</td><td><span class="pill">${c.status}</span></td><td>${c.usage}</td><td><button class="actionBtn" onclick="toast('Client details opened')">Manage</button></td></tr>`).join('')+'</tbody></table>';$('#clientsTable').innerHTML=h}
function renderLeads(){let h='<table class="table"><thead><tr><th>Lead</th><th>Client</th><th>Need</th><th>Est. value</th><th>Captured</th><th>Status</th></tr></thead><tbody>';h+=leads.map(l=>`<tr><td><b>${l.name}</b></td><td>${l.company}</td><td>${l.need}</td><td>${l.value}</td><td>${l.time}</td><td><select><option>New</option><option>Contacted</option><option>Qualified</option><option>Won</option></select></td></tr>`).join('')+'</tbody></table>';$('#leadsTable').innerHTML=h}
function renderThreads(active=0){$('#threadList').innerHTML=threads.map((t,i)=>`<div class="thread ${i===active?'active':''}" data-thread="${i}"><div class="threadTop"><b>${t.name}</b><small>${t.time}</small></div><small>${t.company}</small><p>${t.preview}</p></div>`).join('');$$('[data-thread]').forEach(el=>el.onclick=()=>renderThreads(+el.dataset.thread));const t=threads[active];$('#conversation').innerHTML=`<div class="conversationHead"><b>${t.name}</b><div>${t.company} · AI conversation</div></div><div class="messages">${t.messages.map(m=>`<div class="message ${m[0]==='ai'?'ai':''}">${m[1]}<small>${m[0]==='ai'?'SupportPilot Assistant':'Customer'}</small></div>`).join('')}</div><div class="replyBox"><input placeholder="Type a human reply..."><button class="primaryBtn" onclick="toast('Reply sent')">Send</button></div>`}
function renderAssistants(){$('#assistantGrid').innerHTML=assistants.map(a=>`<article class="assistantCard"><div class="assistantCardTop"><span class="assistantIcon">◆</span><span class="pill">${a[2]}</span></div><h3>${a[0]}</h3><p>${a[1]}</p><div class="assistantMetrics"><div><b>${a[3]}</b><span>Conversations</span></div><div><b>${a[4]}</b><span>Resolution rate</span></div></div><button class="secondaryBtn" onclick="toast('Assistant settings opened')">Configure assistant</button></article>`).join('')}
function renderDocs(){$('#docList').innerHTML=documents.map(d=>`<div class="docRow"><span class="docIcon">▤</span><div><b>${d[0]}</b><small>${d[1]} · ${d[2]}</small></div><button class="actionBtn" onclick="toast('Document options opened')">•••</button></div>`).join('')}
function renderTopics(){const topics=[['Pricing and estimates',92],['Appointment availability',78],['Service questions',64],['Business hours',47],['Coverage areas',35]];$('#topicBars').innerHTML=topics.map(t=>`<div class="topicRow"><b>${t[0]}</b><div class="topicBar"><i style="width:${t[1]}%"></i></div><span>${t[1]}%</span></div>`).join('')}
function csvDownload(){const rows=[['Name','Client','Need','Estimated Value','Captured'],...leads.map(l=>[l.name,l.company,l.need,l.value,l.time])];const blob=new Blob([rows.map(r=>r.map(x=>`"${x}"`).join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='supportpilot-leads.csv';a.click();URL.revokeObjectURL(a.href);toast('Lead report downloaded')}
$$('[data-modal]').forEach(b=>b.onclick=()=>$('#'+b.dataset.modal).classList.add('open'));$('.closeModal').onclick=()=>$('#clientModal').classList.remove('open');$('#clientModal').onclick=e=>{if(e.target.id==='clientModal')e.target.classList.remove('open')};
$('#clientForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),n=f.get('name');clients.push({name:n,industry:f.get('industry'),plan:f.get('plan'),status:'Setup',usage:'0 / 500',initials:n.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()});renderOverview();renderClients();$('#clientModal').classList.remove('open');e.target.reset();toast('Client account created')};
$('#settingsForm').onsubmit=e=>{e.preventDefault();toast('Settings saved')};$('#downloadLeads').onclick=csvDownload;$('#exportBtn').onclick=()=>toast('Dashboard report prepared');$('#analyticsExport').onclick=()=>toast('Analytics report prepared');$('#newAssistant').onclick=()=>toast('Assistant builder opened');$('#uploadDoc').onclick=()=>toast('Select a file to upload');$('#uploadZone').onclick=()=>toast('File upload is ready to connect to cloud storage');
$('#globalSearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase();if(q.length>2){const hit=[...clients,...leads].find(x=>JSON.stringify(x).toLowerCase().includes(q));if(hit)toast(`Found: ${hit.name}`)}});
renderOverview();renderClients();renderLeads();renderThreads();renderAssistants();renderDocs();renderTopics();
